# Generated by Django 4.2.8 on 2023-12-07 14:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='kullaniciadi',
        ),
        migrations.AddField(
            model_name='profil',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
