# Generated by Django 4.2.8 on 2023-12-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0002_remove_profil_kullaniciadi_profil_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='name',
            field=models.CharField(default='empty', max_length=30),
        ),
    ]
