# Generated by Django 4.2.8 on 2023-12-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0003_profil_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(default='smile.png', upload_to='profile_pic'),
        ),
    ]
