# Generated by Django 4.2.8 on 2023-12-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=10000)),
                ('icerik', models.TextField(blank=True, null=True)),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
